services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: api
    env_file:
      - .env
    volumes:
      - ./:/src/
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - warehouse_network
  db:
    image: postgres:14
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - warehouse_network

networks:
  warehouse_network:
    name: warehouse_network
    driver: bridge
